# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Runs a set of commands using the runners shell
      - name: Lint and Test
        run: |
          npm install
          npm run test
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: test-results/junit.xml
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Runs a set of commands using the runners shell
      - name: Lint
        run: |
          npm install
          npm run lint
